# Generated by Django 4.2.1 on 2023-06-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(10, 'Client'), (20, 'General Admin'), (30, 'Manager'), (40, 'Cleaner')], default=10),
        ),
    ]
