# Generated by Django 4.2.1 on 2023-05-21 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_delete_companyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True)),
                ('bedrooms_nmb', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('bathrooms_nmb', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('kitchen_nmb', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('other_rooms_nmb', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('total_area_size', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='bedrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='kitchen_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='other_rooms_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='total_area_size',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.service'),
        ),
    ]
