# Generated by Django 4.2.1 on 2023-05-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_service_total_area_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservice',
            name='hours_duration',
        ),
    ]
