# Generated by Django 4.2.1 on 2023-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_service_bathrooms_nmb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
