# Generated by Django 4.2.1 on 2023-05-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('companies', '0015_remove_companyservice_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
