# Generated by Django 4.2.1 on 2023-05-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('companies', '0016_companyservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='slug',
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.region'),
        ),
    ]
