# Generated by Django 4.2.1 on 2023-05-28 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_remove_companyservice_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_fee_per_area_unit', models.BooleanField(default=False)),
                ('nmb_of_cleaners', models.PositiveIntegerField(default=1)),
                ('hours_duration', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceFeesUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_approved_by_company', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='service_fee',
        ),
    ]
