# Generated by Django 4.2.1 on 2023-05-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_rename_is_approved_by_company_companyservicefeessnapshot_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyservicefeessnapshot',
            old_name='is_approved',
            new_name='is_accepted',
        ),
    ]
