# Generated by Django 4.2.1 on 2023-06-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='zip_code',
        ),
    ]
