# Generated by Django 4.2.1 on 2024-09-28 16:53

from django.db import migrations, models
from apps.utils import images_utils


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_small',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to=images_utils.UploadToPathAndRenameImage(upload_to='companies/logos/small')),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_xsmall',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to=images_utils.UploadToPathAndRenameImage(upload_to='companies/logos/xsmall')),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=images_utils.UploadToPathAndRenameImage(upload_to='companies/logos/initial/')),
        ),
    ]
