# Generated by Django 4.2.16 on 2024-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_company_logo_small_company_logo_xsmall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='e_signed_contract_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
