# Generated by Django 4.2.16 on 2024-12-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_companydocumenttype_companydocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDocument',
        ),
    ]
