# Generated by Django 4.2.16 on 2024-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocumenttype',
            name='order_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
