# Generated by Django 4.2.1 on 2023-05-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0004_alter_assignedcleaner_cleaner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleaners', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedulechange',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cleaner',
        ),
    ]
