# Generated by Django 4.2.1 on 2023-06-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0008_rename_scheduleslot_scheduletimeslot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanerschedule',
            old_name='cleaner',
            new_name='user',
        ),
    ]
