# Generated by Django 4.2.1 on 2023-06-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0009_rename_cleaner_cleanerschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletimeslot',
            name='period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cleaners.scheduleperiod'),
        ),
    ]
