# Generated by Django 4.2.1 on 2023-07-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0012_alter_cleanerschedule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycleanerinvite',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
