# Generated by Django 4.2.1 on 2023-05-28 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0007_apartmentplan_name_apartmentplan_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeesUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='servicefee',
            name='apartment_plan',
        ),
        migrations.RemoveField(
            model_name='servicefee',
            name='service_fee_update',
        ),
        migrations.AddField(
            model_name='service',
            name='apartment_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.apartmentplan'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceFeeUpdate',
        ),
        migrations.AddField(
            model_name='servicefee',
            name='fees_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicefeesupdate'),
        ),
    ]
