# Generated by Django 4.2.1 on 2023-05-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0008_servicefeesupdate_remove_servicefee_apartment_plan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceFeesUpdate',
            new_name='ServiceFeesSnapshot',
        ),
    ]
