# Generated by Django 4.2.1 on 2023-05-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_servicefeesupdate_servicefeessnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefee',
            old_name='fees_update',
            new_name='snapshot',
        ),
    ]
