# Generated by Django 4.2.1 on 2023-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicefee_subcontractor_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefee',
            old_name='fee',
            new_name='client_fee',
        ),
    ]
