# Generated by Django 4.2.1 on 2023-07-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicechecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='checklist',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceChecklistItem',
        ),
    ]
