# Generated by Django 4.2.1 on 2023-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_service_regularity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_area_based_fee',
            field=models.BooleanField(default=False),
        ),
    ]
