# Generated by Django 4.2.1 on 2023-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_cleaningtype_regularitytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
