# Generated by Django 4.2.1 on 2023-05-27 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ServiceUpdate',
            new_name='ApartmentPlan',
        ),
        migrations.RemoveField(
            model_name='servicefee',
            name='service_update',
        ),
        migrations.AddField(
            model_name='servicefee',
            name='apartment_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.apartmentplan'),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='service_fee_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicefeeupdate'),
        ),
    ]
