# Generated by Django 4.2.1 on 2023-05-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicefeeupdate_rename_serviceupdate_apartmentplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
