# Generated by Django 4.2.1 on 2023-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_name_remove_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_chore',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
