# Generated by Django 4.2.1 on 2023-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_is_chore'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentplan',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apartmentplan',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True),
        ),
    ]
