# Generated by Django 4.2.1 on 2023-05-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_fees_update_servicefee_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefee',
            name='is_fee_per_area_unit',
        ),
    ]
