# Generated by Django 4.2.1 on 2023-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_servicefee_is_fee_per_area_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefee',
            name='subcontractor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
