# Generated by Django 4.2.1 on 2023-07-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_remove_booking_regularity_type'),
        ('services', '0015_service_checklist_delete_servicechecklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='regularity_type',
        ),
        migrations.DeleteModel(
            name='RegularityType',
        ),
    ]
