# Generated by Django 4.2.1 on 2023-07-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_service_regularity_type_delete_regularitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='regularity_type',
            field=models.PositiveIntegerField(choices=[(10, 'One time'), (20, 'Regular')], default=10),
        ),
    ]
