# Generated by Django 4.2.1 on 2023-05-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='kitchen_nmb',
            new_name='kitchens_nmb',
        ),
    ]
