# Generated by Django 4.2.1 on 2023-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_kitchen_nmb_place_kitchens_nmb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
