# Generated by Django 4.2.1 on 2023-05-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('clients', '0007_remove_place_bathrooms_nmb_remove_place_bedrooms_nmb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.region'),
        ),
    ]
