# Generated by Django 4.2.1 on 2023-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_place_address_id_place_apartment_nmb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='feature',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
