# Generated by Django 4.2.1 on 2023-06-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_place_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='user',
            new_name='client',
        ),
    ]
