# Generated by Django 4.2.1 on 2023-07-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersession'),
        ('clients', '0013_remove_place_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='user_seesion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usersession'),
        ),
    ]
