# Generated by Django 4.2.1 on 2023-07-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_place_user_seesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='user_seesion',
            new_name='user_session',
        ),
    ]
