# Generated by Django 4.2.1 on 2023-05-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaners', '0001_initial'),
        ('companies', '0001_initial'),
        ('clients', '0001_initial'),
        ('cleanings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktagforclient',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='feedbacktagforcleaner',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='cleaningstatus',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='cleaningaddon',
            name='cleaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='feedback_tags_for_cleaner',
            field=models.ManyToManyField(to='cleanings.feedbacktagforcleaner'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='feedback_tags_for_client',
            field=models.ManyToManyField(to='cleanings.feedbacktagforclient'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.place'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyservice'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaningstatus'),
        ),
        migrations.AddField(
            model_name='assignedcleaner',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaners.cleaner'),
        ),
        migrations.AddField(
            model_name='assignedcleaner',
            name='cleaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning'),
        ),
        migrations.AddField(
            model_name='addon',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
