# Generated by Django 4.2.1 on 2023-05-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('cleanings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktagforclient',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='feedbacktagforcleaner',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='cleaningstatus',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='cleaningaddon',
            name='cleaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning'),
        ),
    ]
