# Generated by Django 4.2.1 on 2023-05-19 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_place_bathrooms_nmb_place_bedrooms_nmb_and_more'),
        ('cleanings', '0004_alter_assignedcleaner_cleaner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scheduled_start_dt', models.DateTimeField()),
                ('scheduled_end_dt', models.DateTimeField()),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
