# Generated by Django 4.2.1 on 2023-05-27 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_place_bathrooms_nmb_remove_place_bedrooms_nmb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanings', '0007_remove_cleaning_client_remove_cleaning_place_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleaningRequest',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='cleaning',
            old_name='request',
            new_name='booking',
        ),
    ]
