# Generated by Django 4.2.1 on 2023-05-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_cleaningtype_regularitytype_and_more'),
        ('cleanings', '0011_remove_regularitytype_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaning_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.cleaningtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='regularity_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.regularitytype'),
        ),
    ]
