# Generated by Django 4.2.1 on 2023-05-28 18:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_delete_companyservice_and_more'),
        ('services', '0008_servicefeesupdate_remove_servicefee_apartment_plan_and_more'),
        ('cleanings', '0013_cleaningservice_service_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cleaning_type',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='add_ons_fee',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='total_fee_final',
        ),
        migrations.RemoveField(
            model_name='cleaningstatus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feedbacktagforcleaner',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feedbacktagforclient',
            name='company',
        ),
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_fee_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CleaningService',
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.booking'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='company_service_fee_reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyservicefee'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service_fee_reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicefee'),
        ),
    ]
