# Generated by Django 4.2.1 on 2023-05-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0016_remove_bookingservice_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaning',
            old_name='is_end_match_location',
            new_name='is_end_match_cleaning_location',
        ),
        migrations.RenameField(
            model_name='cleaning',
            old_name='is_start_match_location',
            new_name='is_start_match_cleaning_location',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='status',
        ),
    ]
