# Generated by Django 4.2.1 on 2023-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0017_rename_is_end_match_location_cleaning_is_end_match_cleaning_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Not started'), (20, 'Cleaner is on the way'), (30, 'Started'), (40, 'Completed'), (50, 'Not completed')], default=10),
        ),
    ]
