# Generated by Django 4.2.1 on 2023-05-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0018_cleaning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='status',
        ),
    ]
