# Generated by Django 4.2.1 on 2023-05-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0019_remove_cleaning_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Not assigned'), (20, 'Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed'), (70, 'Cancelled by company'), (80, 'Cancelled by service')], default=10),
        ),
    ]
