# Generated by Django 4.2.1 on 2023-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0022_rename_assignedcleaner_cleanerforcleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='scheduled_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='scheduled_end_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='scheduled_start_dt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
