# Generated by Django 4.2.1 on 2023-06-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0023_cleaning_scheduled_date_cleaning_scheduled_end_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='feedback_tags_for_cleaner',
            field=models.ManyToManyField(default=None, null=True, to='cleanings.feedbacktagforcleaner'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='feedback_tags_for_client',
            field=models.ManyToManyField(default=None, null=True, to='cleanings.feedbacktagforclient'),
        ),
    ]
