# Generated by Django 4.2.1 on 2023-06-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0025_alter_cleaning_feedback_tags_for_cleaner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='scheduled_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='scheduled_end_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='scheduled_start_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
