# Generated by Django 4.2.1 on 2023-06-17 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanings', '0026_alter_cleaning_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='feedback_tags_for_cleaner',
            field=models.ManyToManyField(blank=True, default=None, to='cleanings.feedbacktagforcleaner'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='feedback_tags_for_client',
            field=models.ManyToManyField(blank=True, default=None, to='cleanings.feedbacktagforclient'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Not assigned'), (20, 'Assigned, Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed. Issue Reported'), (70, 'Cancelled by company'), (80, 'Cancelled by service')], default=10),
        ),
        migrations.CreateModel(
            name='CleaningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('cleaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
