# Generated by Django 4.2.1 on 2023-06-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0028_rename_cleaningmessage_cleaningchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningchatmessage',
            old_name='message',
            new_name='text',
        ),
    ]
