# Generated by Django 4.2.1 on 2023-06-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0029_rename_message_cleaningchatmessage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='feedback_for_cleaner',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='feedback_for_client',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='feedback_tags_for_cleaner',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='feedback_tags_for_client',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='score_for_cleaner',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='score_for_client',
        ),
        migrations.DeleteModel(
            name='FeedbackTagForCleaner',
        ),
        migrations.DeleteModel(
            name='FeedbackTagForClient',
        ),
    ]
