# Generated by Django 4.2.1 on 2023-06-17 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0030_remove_cleaning_feedback_for_cleaner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(10, 'Not assigned'), (20, 'Assigned, Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed. Issue Reported'), (70, 'Cancelled by company'), (80, 'Cancelled by service')])),
                ('cleaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
