# Generated by Django 4.2.1 on 2023-06-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0031_cleaningstatuschange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleaningStatus',
        ),
    ]
