# Generated by Django 4.2.1 on 2023-06-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_zipcode_remove_regionzipcode_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionzipcode',
            name='zip_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.zipcode'),
        ),
    ]
