# Generated by Django 4.2.1 on 2023-07-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_country_name_country_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionzipcode',
            unique_together=set(),
        ),
    ]
