# Generated by Django 4.2.1 on 2023-07-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_regionzipcode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionzipcode',
            name='zip_code',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.zipcode'),
        ),
    ]
