# Generated by Django 4.2.1 on 2023-06-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0005_companycleanerinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='relevant_since_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_change',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday_from',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday_to',
        ),
        migrations.DeleteModel(
            name='ScheduleChange',
        ),
    ]
