# Generated by Django 4.2.1 on 2023-06-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0007_cleanerschedule_scheduleperiod_scheduleslot_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleSlot',
            new_name='ScheduleTimeSlot',
        ),
        migrations.RenameField(
            model_name='cleanerschedule',
            old_name='schedule_period',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='cleanerschedule',
            old_name='schedule_slot',
            new_name='time_slot',
        ),
    ]
