# Generated by Django 4.2.1 on 2023-06-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0010_scheduletimeslot_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerschedule',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
