# Generated by Django 4.2.1 on 2023-06-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0011_alter_cleanerschedule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerschedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
