# Generated by Django 4.2.16 on 2024-09-28 18:39

import apps.utils.images_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.utils.images_utils.UploadToPathAndRenameImage(upload_to='users/images/initial')),
        ),
        migrations.AddField(
            model_name='user',
            name='image_small',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to=apps.utils.images_utils.UploadToPathAndRenameImage(upload_to='users/images/small')),
        ),
        migrations.AddField(
            model_name='user',
            name='image_xsmall',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to=apps.utils.images_utils.UploadToPathAndRenameImage(upload_to='users/images/xsmall')),
        ),
    ]
