# Generated by Django 4.2.16 on 2024-09-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_image_user_image_small_user_image_xsmall'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
