# Generated by Django 4.2.16 on 2024-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contact_by_email',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_contact_by_sms',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
