# Generated by Django 4.2.16 on 2024-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_is_contact_by_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_contact_by_email',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No'), (None, 'Not chosen')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_contact_by_sms',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No'), (None, 'Not chosen')], default=None, null=True),
        ),
    ]
