# Generated by Django 4.2.16 on 2024-09-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverificationdocument',
            old_name='file_type',
            new_name='document_type',
        ),
        migrations.AlterField(
            model_name='userverificationdocument',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='users/verification_documents'),
        ),
    ]
