# Generated by Django 4.2.16 on 2024-09-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_file_type_userverificationdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
