# Generated by Django 4.2.16 on 2024-09-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userverificationdocument_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdocument',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'New'), (20, 'Approved'), (30, 'Rejected')], default=None, null=True),
        ),
    ]
