# Generated by Django 4.2.16 on 2024-09-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userverificationdocument_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverificationdocument',
            name='status',
        ),
    ]
