# Generated by Django 4.2.16 on 2024-09-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_userverificationdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationdocument',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(5, 'Not Uploaded'), (10, 'New'), (20, 'Approved'), (30, 'Rejected')], default=None, null=True),
        ),
    ]
