# Generated by Django 4.2.16 on 2024-09-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userverificationdocument_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverificationdocument',
            name='status',
        ),
    ]
