# Generated by Django 4.2.16 on 2024-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userverificationdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(choices=[(10, 'Client'), (20, 'General Admin'), (30, 'Manager'), (40, 'Cleaner'), (50, 'Support Agent')], default=10),
        ),
    ]
