# Generated by Django 4.2.16 on 2024-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_service_is_area_based_fee'),
        ('users', '0024_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cleaner_preferred_districts',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cleaner_preferred_service_types',
            field=models.ManyToManyField(null=True, to='services.service'),
        ),
    ]
