# Generated by Django 4.2.1 on 2023-05-18 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.cleaningtype'),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='regularity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.regularitytype'),
        ),
        migrations.AddField(
            model_name='cleaningtype',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
