# Generated by Django 4.2.1 on 2023-05-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularitytype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='cleaning_type',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='regularity_type',
        ),
        migrations.DeleteModel(
            name='CleaningType',
        ),
        migrations.DeleteModel(
            name='RegularityType',
        ),
    ]
