# Generated by Django 4.2.1 on 2023-05-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0007_remove_cleaning_client_remove_cleaning_place_and_more'),
        ('companies', '0003_remove_regularitytype_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='cleaning_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaningtype'),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='regularity_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cleanings.regularitytype'),
        ),
    ]
