# Generated by Django 4.2.1 on 2023-05-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyservice_cleaning_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
