# Generated by Django 4.2.1 on 2023-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_service_remove_companyservice_bathrooms_nmb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_area_size',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='is_fee_per_area_unit',
            field=models.BooleanField(default=False),
        ),
    ]
