# Generated by Django 4.2.1 on 2023-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_companyservice_hours_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='hours_duration',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
