# Generated by Django 4.2.1 on 2023-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_companyservice_cleaning_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bedrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='service',
            name='kitchen_nmb',
        ),
        migrations.RemoveField(
            model_name='service',
            name='other_rooms_nmb',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='bathrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='bedrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='kitchen_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='other_rooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
