# Generated by Django 4.2.1 on 2023-05-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companyservice_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyservice',
            old_name='kitchen_nmb',
            new_name='kitchens_nmb',
        ),
    ]
