# Generated by Django 4.2.1 on 2023-05-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_rename_kitchen_nmb_companyservice_kitchens_nmb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cleaning_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='regularity_type',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='bedrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='kitchens_nmb',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='other_rooms_nmb',
        ),
    ]
