# Generated by Django 4.2.1 on 2023-05-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('companies', '0014_remove_service_cleaning_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservice',
            name='service',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='service_fee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicefee'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
