# Generated by Django 4.2.1 on 2023-05-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0013_cleaningservice_service_fee_and_more'),
        ('companies', '0018_companyservicefee_companyservicefeesupdate_and_more'),
        ('services', '0007_apartmentplan_name_apartmentplan_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyService',
        ),
        migrations.AddField(
            model_name='companyservicefeesupdate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyservicefeesupdate',
            name='service_fee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicefee'),
        ),
        migrations.AddField(
            model_name='companyservicefee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyservicefee',
            name='fees_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyservicefeesupdate'),
        ),
        migrations.AddField(
            model_name='companyservicefee',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
