# Generated by Django 4.2.1 on 2023-05-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicefeesupdate_remove_servicefee_apartment_plan_and_more'),
        ('companies', '0019_delete_companyservice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyServiceFeesUpdate',
            new_name='CompanyServiceFeesSnapshot',
        ),
        migrations.RenameField(
            model_name='companyservicefee',
            old_name='fees_update',
            new_name='fees_snapshot',
        ),
    ]
