# Generated by Django 4.2.1 on 2023-05-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_rename_companyservicefeesupdate_companyservicefeessnapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyservicefee',
            old_name='fees_snapshot',
            new_name='snapshot',
        ),
    ]
