# Generated by Django 4.2.1 on 2023-05-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_rename_fees_snapshot_companyservicefee_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservicefee',
            name='is_fee_per_area_unit',
        ),
    ]
