# Generated by Django 4.2.1 on 2023-05-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_servicefee_is_fee_per_area_unit'),
        ('companies', '0022_remove_companyservicefee_is_fee_per_area_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservicefeessnapshot',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='companyservicefeessnapshot',
            name='service_fees_snapshot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicefeessnapshot'),
        ),
    ]
