# Generated by Django 4.2.1 on 2023-05-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_remove_companyservicefeessnapshot_service_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyservicefeessnapshot',
            old_name='is_approved_by_company',
            new_name='is_approved',
        ),
    ]
