# Generated by Django 4.2.1 on 2023-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_rename_is_approved_companyservicefeessnapshot_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservicefeessnapshot',
            name='accepted_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
