# Generated by Django 4.2.16 on 2024-10-27 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_supportticketstatuschange_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
