"""
Django settings for cleaning project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

root = environ.Path(__file__) - 2
env = environ.Env()
environ.Env.read_env('.env')  # reading .env file
IS_ON_PROD = env.bool("IS_ON_PROD", default=False)
IS_ON_TEST = env.bool("IS_ON_TEST", default=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default='django-insecure-s61gx1!_jrjb%79k^0^w#g4v8))9w+l!i-qh%5sseev01hj&1*')

# SECURITY WARNING: don't run with debug turned on in production!
if IS_ON_PROD or IS_ON_TEST:
    DEBUG = env.bool("DEBUG", default=False)
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
    CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
else:
    DEBUG = True
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'cleaners',
    'cleanings',
    'clients',
    'companies',
    'subscriptions',
    'users',

    # packages
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'axes',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'cleaning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cleaning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if IS_ON_TEST or IS_ON_PROD:
    IS_SSL_FOR_DB = env.bool("IS_SSL_FOR_DB", default=False)
    DB_SSL_PATH = env.str("DB_SSL_PATH", default="")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env.str("DB_NAME"),
            'USER': env.str("DB_USERNAME"),
            'PASSWORD': env.str("DB_PASSWORD"),
            'HOST': env.str("DB_HOST"),
            'PORT': env.str("DB_PORT", default="5432"),
        },
    }

    if IS_SSL_FOR_DB:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': 'prefer',
            'sslrootcert': env.str("DB_SSL_CERTIFICATE", default=DB_SSL_PATH),  # /home/ubuntu/.ssh/ca-certificate.crt
        }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static", "static_prod")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static", "static_dev"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""Custom settings"""
SITE_ID = 1

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'users.User'
USE_THOUSAND_SEPARATOR = True

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

ACCOUNT_FORMS = {
    'login': 'users.allauth_forms.CustomLoginForm',
    'signup': 'users.allauth_forms.CustomSignupForm',
    'reset_password': 'users.allauth_forms.CustomResetPasswordForm'
}

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_VERIFICATION = env.str("ACCOUNT_EMAIL_VERIFICATION", default="mandatory")  # none
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = None  # this is managed by django-axes
ACCOUNT_USER_DISPLAY = lambda user: user.email  # returns email instead of username (which is by default)

if IS_ON_PROD:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = env.str("ACCOUNT_DEFAULT_HTTP_PROTOCOL", default="https")
else:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"


AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_FAILURE_LIMIT = env.int("AXES_FAILURE_LIMIT", default=3)
AXES_COOLOFF_TIME = env.int("AXES_COOLOFF_TIME", default=3)
AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_FORM_FIELD = 'login'  # custom django-allauth login form is adjusted accordingly
AXES_META_PRECEDENCE_ORDER = env.list("AXES_META_PRECEDENCE_ORDER", default=["HTTP_X_FORWARDED_FOR"])

LOGIN_REDIRECT_URL = "/"

FROM_EMAIL = env.str("FROM_EMAIL", default="hello@tonythenotary.com")
DEFAULT_FROM_EMAIL = FROM_EMAIL

if IS_ON_PROD:
    IS_SENDING_EMAILS = env.bool("IS_SENDING_EMAILS", default=True)
else:
    IS_SENDING_EMAILS = env.bool("IS_SENDING_EMAILS", default=False)

if not IS_SENDING_EMAILS:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_HOST_USER = env.str("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD")
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True


RECAPTCHA_PUBLIC_KEY = env.str("RECAPTCHA_PUBLIC_KEY", default="")
RECAPTCHA_PRIVATE_KEY = env.str("RECAPTCHA_PRIVATE_KEY", default="")

IS_CAPTCHA = env.bool("IS_CAPTCHA", default=IS_ON_PROD or IS_ON_TEST)

HIJACK_INSERT_BEFORE = None  # project has its own notification mechanism

if IS_ON_PROD:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,
        'formatters': {
            'verbose': {
                'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
            },
        },
        'handlers': {
            'console': {
                'level': 'NOTSET',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            },
            'console1': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            }
        },
        'loggers': {
            '': {
                'handlers': ['console'],
                'level': 'NOTSET',
            },
            'django.request': {
                'handlers': ['console1'],
                'propagate': False,
                'level': 'INFO'
            }
        }
    }