"""
Django settings for cleaning project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

root = environ.Path(__file__) - 2
env = environ.Env()
environ.Env.read_env('.env')  # reading .env file
IS_ON_PROD = env.bool("IS_ON_PROD", default=False)
IS_ON_TEST = env.bool("IS_ON_TEST", default=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default='django-insecure-s61gx1!_jrjb%79k^0^w#g4v8))9w+l!i-qh%5sseev01hj&1*')

# SECURITY WARNING: don't run with debug turned on in production!
if IS_ON_PROD or IS_ON_TEST:
    DEBUG = env.bool("DEBUG", default=False)
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
    CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
else:
    DEBUG = True
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.bookings',
    'apps.cleaners',
    'apps.cleanings',
    'apps.clients',
    'apps.companies',
    'apps.locations',
    'apps.notifications',
    'apps.services',
    'apps.subscriptions',
    'apps.support',
    'apps.users',
    'apps.utils',

    # packages
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'axes',
    'crispy_forms',
    'crispy_bootstrap5',
    'captcha',
    'crequest',
    'django_cleanup.apps.CleanupConfig',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'axes.middleware.AxesMiddleware',
    'crequest.middleware.CrequestMiddleware',
]

ROOT_URLCONF = 'cleaning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cleaning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if IS_ON_TEST or IS_ON_PROD:
    IS_SSL_FOR_DB = env.bool("IS_SSL_FOR_DB", default=False)
    DB_SSL_PATH = env.str("DB_SSL_PATH", default="")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env.str("DB_NAME"),
            'USER': env.str("DB_USERNAME"),
            'PASSWORD': env.str("DB_PASSWORD"),
            'HOST': env.str("DB_HOST"),
            'PORT': env.str("DB_PORT", default="5432"),
        },
    }

    if IS_SSL_FOR_DB:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': 'prefer',
            'sslrootcert': env.str("DB_SSL_CERTIFICATE", default=DB_SSL_PATH),  # /home/ubuntu/.ssh/ca-certificate.crt
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static", "static_prod")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static", "static_dev"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""Custom settings"""
SITE_ID = 1

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'users.User'
USE_THOUSAND_SEPARATOR = True

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

ACCOUNT_FORMS = {
    'login': 'apps.users.allauth_forms.CustomLoginForm',
    'signup': 'apps.users.allauth_forms.CustomSignupForm',
    'reset_password': 'apps.users.allauth_forms.CustomResetPasswordForm'
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': env.str("GOOGLE_API_CLIENT_ID", default=""),
            'secret': env.str("GOOGLE_API_SECRET", default=""),
            'key': ''
        }
    }
}

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_VERIFICATION = env.str("ACCOUNT_EMAIL_VERIFICATION", default="mandatory")  # none

ACCOUNT_LOGIN_ATTEMPTS_LIMIT = None  # this is managed by django-axes
ACCOUNT_USER_DISPLAY = lambda user: user.email  # returns email instead of username (which is by default)

if IS_ON_PROD:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = env.str("ACCOUNT_DEFAULT_HTTP_PROTOCOL", default="https")
else:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"


AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_FAILURE_LIMIT = env.int("AXES_FAILURE_LIMIT", default=3)
AXES_COOLOFF_TIME = env.int("AXES_COOLOFF_TIME", default=3)
AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_FORM_FIELD = 'login'  # custom django-allauth login form is adjusted accordingly
AXES_META_PRECEDENCE_ORDER = env.list("AXES_META_PRECEDENCE_ORDER", default=["HTTP_X_FORWARDED_FOR"])

LOGIN_REDIRECT_URL = "/"

FROM_EMAIL = env.str("FROM_EMAIL", default="hello@tidify.co")
DEFAULT_FROM_EMAIL = FROM_EMAIL

IS_SENDING_EMAILS = env.bool("IS_SENDING_EMAILS", default=IS_ON_PROD)

if not IS_SENDING_EMAILS:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_HOST_USER = env.str("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD")
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True

IS_CAPTCHA = env.bool("IS_CAPTCHA", default=IS_ON_PROD or IS_ON_TEST)
RECAPTCHA_PUBLIC_KEY = env.str("RECAPTCHA_PUBLIC_KEY", default="")
RECAPTCHA_PRIVATE_KEY = env.str("RECAPTCHA_PRIVATE_KEY", default="")

HIJACK_INSERT_BEFORE = None  # project has its own notification mechanism
ONE_TIME_REGULARITY_NAME = env.str("ONE_TIME_REGULARITY_NAME", default="One time")
DEFAULT_PROFIT_RATE = env.float("DEFAULT_PROFIT_RATE", default=30)

# for schedule
TIME_SLOTS = env.list("TIME_SLOTS", default=["8:00-13:00", "13:00-18:00"])

MAPBOX_TOKEN = env.str("MAPBOX_TOKEN", default="")

STRIPE_PUBLIC_KEY = env.str("STRIPE_PUBLIC_KEY", default="")
STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = env.str("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_CONNECT_PLATFORM_FEE_PERCENT = env.float("STRIPE_CONNECT_PLATFORM_FEE_PERCENT", default=15.0)

# # Your Account SID from twilio.com/console
# account_sid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#
# # Your Auth Token from twilio.com/console
# auth_token = "your_auth_token"
TWILIO_ACCOUNT_SID = env.str("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = env.str("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_FROM = env.str("TWILIO_PHONE_FROM")

# 1 hour
DUPLICATED_NOTIFICATION_COOLOFF_SECONDS = env.int("DUPLICATED_NOTIFICATION_COOLOFF_SECONDS", default=60*60)

if IS_ON_PROD:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,
        'formatters': {
            'verbose': {
                'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
            },
        },
        'handlers': {
            'console_notset': {
                'level': 'NOTSET',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            },
            'console_info': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose'
            },
        },
        'loggers': {
            '': {
                'handlers': ['console_notset'],
                'level': 'NOTSET',
            },
            'django': {
                'handlers': ['console_info'],
                'propagate': False,
                'level': 'ERROR'
            },
        }
    }

STRIPE_PRODUCT_ID = env.str("STRIPE_PRODUCT_ID")

IMPORT_EXPORT_ESCAPE_FORMULAE_ON_EXPORT = True

# ── API Layer Configuration ───────────────────────────────────────────
from .api_settings import *  # noqa: F401,F403

# Extend INSTALLED_APPS with DRF, JWT, CORS, and the API app
INSTALLED_APPS += API_APPS  # noqa: F405

# Insert CORS middleware before CommonMiddleware
for mw, before in API_MIDDLEWARE_INSERT:  # noqa: F405
    try:
        idx = MIDDLEWARE.index(before)
        MIDDLEWARE.insert(idx, mw)
    except ValueError:
        MIDDLEWARE.append(mw)

# If JWT_SIGNING_KEY is empty, fall back to SECRET_KEY
if not SIMPLE_JWT.get("SIGNING_KEY"):  # noqa: F405
    SIMPLE_JWT["SIGNING_KEY"] = SECRET_KEY  # noqa: F405

NOTIFICATION_EMAILS = env.list("NOTIFICATION_EMAILS", default=[])
NOT_STARTED_ALERTING_PERIOD_MINUTES = env.int("NOT_STARTED_ALERTING_PERIOD_MINUTES", default=15)

ACCOUNT_ADAPTER = 'cleaning.account_adapter.CustomAccountAdapter'
IS_SIGNUP_OPEN = env.bool("IS_SIGNUP_OPEN", default=False)
DAILY_LIMIT_FOR_MAPBOX_AUTOCOMPLETE = env.int("DAILY_LIMIT_FOR_MAPBOX_AUTOCOMPLETE", default=100)
