# Generated by Django 4.2.1 on 2023-05-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcleaner',
            name='cleaner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
