# Generated by Django 4.2.1 on 2023-05-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0005_cleaningrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='request',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaningrequest'),
        ),
    ]
