# Generated by Django 4.2.1 on 2023-05-19 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_regularitytype_company_and_more'),
        ('cleanings', '0006_cleaning_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='place',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='scheduled_end_dt',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='scheduled_start_dt',
        ),
        migrations.CreateModel(
            name='RegularityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='cleaning_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaningtype'),
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='regularity_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanings.regularitytype'),
        ),
    ]
