# Generated by Django 4.2.1 on 2023-05-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0008_rename_cleaningrequest_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cleanings.booking'),
        ),
    ]
