# Generated by Django 4.2.1 on 2023-05-27 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_rename_kitchen_nmb_companyservice_kitchens_nmb'),
        ('cleanings', '0009_alter_cleaning_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cleaningaddon',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='service',
        ),
        migrations.DeleteModel(
            name='AddOn',
        ),
        migrations.DeleteModel(
            name='CleaningAddOn',
        ),
        migrations.AddField(
            model_name='cleaningservice',
            name='cleaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning'),
        ),
        migrations.AddField(
            model_name='cleaningservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyservice'),
        ),
    ]
