# Generated by Django 4.2.1 on 2023-05-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0010_cleaningservice_remove_cleaningaddon_cleaning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularitytype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cleaning_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='regularity_type',
        ),
        migrations.DeleteModel(
            name='CleaningType',
        ),
        migrations.DeleteModel(
            name='RegularityType',
        ),
    ]
