# Generated by Django 4.2.1 on 2023-05-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_companyservicefee_companyservicefeesupdate_and_more'),
        ('services', '0007_apartmentplan_name_apartmentplan_slug'),
        ('cleanings', '0012_booking_cleaning_type_booking_regularity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningservice',
            name='service_fee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyservicefee'),
        ),
        migrations.AlterField(
            model_name='cleaningservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
