# Generated by Django 4.2.1 on 2023-05-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0014_bookingservice_remove_booking_cleaning_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='end_coordinates',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='is_end_match_location',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='is_start_match_location',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='start_coordinates',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
