# Generated by Django 4.2.1 on 2023-05-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('cleanings', '0015_cleaning_end_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='company_service_fee_reference',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service_fee_reference',
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingService',
        ),
    ]
