# Generated by Django 4.2.1 on 2023-06-10 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanings', '0021_alter_cleaning_is_end_match_cleaning_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignedCleaner',
            new_name='CleanerForCleaning',
        ),
    ]
