# Generated by Django 4.2.1 on 2023-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0024_alter_cleaning_feedback_tags_for_cleaner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='feedback_tags_for_cleaner',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cleanings.feedbacktagforcleaner'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='feedback_tags_for_client',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cleanings.feedbacktagforclient'),
        ),
    ]
