# Generated by Django 4.2.1 on 2023-06-17 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanings', '0027_alter_cleaning_feedback_tags_for_cleaner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleaningMessage',
            new_name='CleaningChatMessage',
        ),
    ]
