# Generated by Django 4.2.1 on 2023-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0033_alter_cleaning_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='end_coordinates_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='start_coordinates_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
