# Generated by Django 4.2.16 on 2024-10-13 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0034_cleaning_end_coordinates_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('cleaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
