# Generated by Django 4.2.16 on 2024-10-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0035_cleaninginvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='initially_scheduled_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
