# Generated by Django 4.2.16 on 2024-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0036_cleaning_initially_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninginvoice',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
