# Generated by Django 4.2.16 on 2024-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0037_cleaninginvoice_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninginvoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
