# Generated by Django 4.2.16 on 2024-10-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0038_cleaninginvoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninginvoice',
            name='stripe_invoice_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
