# Generated by Django 4.2.16 on 2024-10-28 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_company_logo_small_company_logo_xsmall_and_more'),
        ('bookings', '0041_booking_stripe_customer_id'),
        ('cleanings', '0039_cleaninginvoice_stripe_invoice_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('booking', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
