# Generated by Django 4.2.16 on 2024-10-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_booking_stripe_customer_id'),
        ('cleanings', '0040_cleaningspecialrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningspecialrequest',
            name='booking',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
