# Generated by Django 4.2.16 on 2024-10-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_booking_stripe_customer_id'),
        ('companies', '0032_company_logo_small_company_logo_xsmall_and_more'),
        ('cleanings', '0041_alter_cleaningspecialrequest_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleaningSpecialRequest',
            new_name='SpecialCleaningRequest',
        ),
    ]
