# Generated by Django 4.2.16 on 2024-10-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0042_rename_cleaningspecialrequest_specialcleaningrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialcleaningrequest',
            name='fee',
        ),
    ]
