# Generated by Django 4.2.16 on 2024-10-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0043_remove_specialcleaningrequest_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcleaningrequest',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
