# Generated by Django 4.2.16 on 2024-11-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_booking_stripe_customer_id'),
        ('cleanings', '0044_specialcleaningrequest_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcleaningrequest',
            name='cleaning',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanings.cleaning'),
        ),
        migrations.AlterField(
            model_name='specialcleaningrequest',
            name='booking',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
