# Generated by Django 4.2.16 on 2024-11-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0045_specialcleaningrequest_cleaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcleaningrequest',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='specialcleaningrequest',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'New'), (20, 'Accepted'), (40, 'Cancelled by Company'), (50, 'Cancelled by Service')], default=10, null=True),
        ),
    ]
