# Generated by Django 4.2.16 on 2024-11-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0042_booking_special_request'),
        ('cleanings', '0046_specialcleaningrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialcleaningrequest',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
