# Generated by Django 4.2.16 on 2024-12-01 21:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0047_alter_specialcleaningrequest_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTagForCleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackTagForClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cleaning',
            name='feedback_for_cleaner',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='feedback_for_client',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='score_for_cleaner',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='score_for_client',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='feedback_tags_for_cleaner',
            field=models.ManyToManyField(blank=True, default=None, to='cleanings.feedbacktagforcleaner'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='feedback_tags_for_client',
            field=models.ManyToManyField(blank=True, default=None, to='cleanings.feedbacktagforclient'),
        ),
    ]
