# Generated by Django 4.2.16 on 2024-12-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0048_feedbacktagforcleaner_feedbacktagforclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Waiting assignment'), (20, 'Assigned, Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed. Issue Reported'), (70, 'Cancelled by company'), (80, 'Cancelled by service'), (90, 'Cancelled by client')], default=10),
        ),
        migrations.AlterField(
            model_name='cleaningstatuschange',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Waiting assignment'), (20, 'Assigned, Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed. Issue Reported'), (70, 'Cancelled by company'), (80, 'Cancelled by service'), (90, 'Cancelled by client')]),
        ),
    ]
