# Generated by Django 4.2.16 on 2024-12-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0050_alter_cleaning_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninginvoice',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cleaninginvoice',
            name='stripe_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
