# Generated by Django 4.2.16 on 2024-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0051_cleaninginvoice_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='payment_status',
            field=models.PositiveIntegerField(choices=[(10, 'Not paid'), (20, 'Partially paid'), (30, 'Fully paid')], default=10),
        ),
    ]
