# Generated by Django 4.2.16 on 2024-12-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0052_cleaning_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='payment_status',
            field=models.PositiveIntegerField(choices=[(10, 'Not paid'), (20, 'Partially paid'), (30, 'Paid')], default=10),
        ),
    ]
