# Generated by Django 4.2.16 on 2024-12-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_companydocumenttype_order_index'),
        ('cleanings', '0053_alter_cleaning_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
