# Generated by Django 4.2.16 on 2024-12-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0054_alter_cleaning_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Waiting for cleaner assignment'), (20, 'Assigned, Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed. Issue Reported'), (70, 'Canceled by company'), (80, 'Canceled by service'), (90, 'Canceled by client')], default=10),
        ),
        migrations.AlterField(
            model_name='cleaningstatuschange',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'Waiting for cleaner assignment'), (20, 'Assigned, Not started'), (30, 'Cleaner is on the way'), (40, 'Started'), (50, 'Completed'), (60, 'Not completed. Issue Reported'), (70, 'Canceled by company'), (80, 'Canceled by service'), (90, 'Canceled by client')]),
        ),
    ]
