# Generated by Django 4.2.16 on 2025-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0055_alter_cleaning_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
    ]
