# Generated by Django 4.2.1 on 2023-05-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_place_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='bedrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='kitchens_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='other_rooms_nmb',
        ),
    ]
