# Generated by Django 4.2.1 on 2023-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_place_bathrooms_nmb_remove_place_bedrooms_nmb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='bathrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bedrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='kitchens_nmb',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='other_rooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
