# Generated by Django 4.2.1 on 2023-05-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_place_bathrooms_nmb_place_bedrooms_nmb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='bedrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='kitchens_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='other_rooms_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='total_area_size',
        ),
    ]
