# Generated by Django 4.2.1 on 2023-06-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_country_alter_regionzipcode_unique_together_state_and_more'),
        ('clients', '0008_place_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address_id',
        ),
        migrations.AddField(
            model_name='place',
            name='apartment_nmb',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country'),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.state'),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.zipcode'),
        ),
    ]
