# Generated by Django 4.2.1 on 2023-07-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_place_session_id_alter_place_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='session_id',
        ),
    ]
