# Generated by Django 4.2.1 on 2023-07-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_place_user_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
        migrations.DeleteModel(
            name='PlaceType',
        ),
    ]
