# Generated by Django 4.2.1 on 2023-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_remove_place_type_delete_placetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.PositiveIntegerField(choices=[(10, 'Apartment'), (20, 'House'), (30, 'Commercial')], default=10),
        ),
    ]
