# Generated by Django 4.2.1 on 2023-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='area_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='bathrooms_nmb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='bedrooms_nmb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
