# Generated by Django 4.2.1 on 2023-07-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_place_area_size_place_bathrooms_nmb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='area_size',
        ),
        migrations.RemoveField(
            model_name='place',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='place',
            name='bedrooms_nmb',
        ),
    ]
