# Generated by Django 4.2.1 on 2023-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_remove_place_area_size_remove_place_bathrooms_nmb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='area_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bathrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bedrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
