# Generated by Django 4.2.16 on 2025-01-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_mapboxrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapboxrequest',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
