# Generated by Django 4.2.1 on 2023-05-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_discountcode_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
