# Generated by Django 4.2.1 on 2023-06-17 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_feedbacktagforcleaner_feedbacktagforclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(10, 'New'), (20, 'In work'), (30, 'Completed'), (40, 'Rejected'), (50, 'Cancelled by client')])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
