# Generated by Django 4.2.1 on 2023-06-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_bookingstatuschange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'In work'), (30, 'Completed'), (40, 'Cancelled by Service'), (50, 'Cancelled by client')], default=10),
        ),
        migrations.AlterField(
            model_name='bookingstatuschange',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'In work'), (30, 'Completed'), (40, 'Cancelled by Service'), (50, 'Cancelled by client')]),
        ),
    ]
