# Generated by Django 4.2.1 on 2023-06-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='client',
        ),
    ]
