# Generated by Django 4.2.1 on 2023-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='stripe_id',
            new_name='stripe_intent_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_tip_intent_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
