# Generated by Django 4.2.1 on 2023-06-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_rename_stripe_id_booking_stripe_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_tip_paid',
            field=models.BooleanField(default=True),
        ),
    ]
