# Generated by Django 4.2.1 on 2023-06-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_is_paid_booking_is_tip_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='stripe_intent_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='stripe_tip_intent_id',
            new_name='stripe_tip_payment_intent_id',
        ),
    ]
