# Generated by Django 4.2.1 on 2023-06-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_rename_stripe_intent_id_booking_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_tip_paid',
        ),
    ]
