# Generated by Django 4.2.1 on 2023-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_remove_booking_is_paid_remove_booking_is_tip_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_tip_paid',
            field=models.BooleanField(default=False),
        ),
    ]
