# Generated by Django 4.2.1 on 2023-06-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_is_paid_booking_is_tip_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='discount',
            new_name='discount_amount',
        ),
    ]
