# Generated by Django 4.2.1 on 2023-07-03 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0023_rename_discount_booking_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usersession'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
