# Generated by Django 4.2.1 on 2023-07-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_booking_regularity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_end_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_start_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
