# Generated by Django 4.2.1 on 2023-07-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_place_type'),
        ('bookings', '0028_alter_booking_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.place'),
        ),
    ]
