# Generated by Django 4.2.1 on 2023-07-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_booking_area_size_booking_bathrooms_nmb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='area_size',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bathrooms_nmb',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bedrooms_nmb',
        ),
    ]
