# Generated by Django 4.2.1 on 2023-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_remove_booking_area_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bathrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bedrooms_nmb',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
