# Generated by Django 4.2.1 on 2024-09-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_alter_zipcode_value'),
        ('bookings', '0036_alter_booking_score_for_cleaner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region'),
        ),
    ]
