# Generated by Django 4.2.16 on 2024-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_discountcode_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='regularity',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'Weekly'), (20, 'Bi-weekly'), (30, 'Monthly')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.PositiveIntegerField(choices=[(10, 'One Time'), (20, 'Regular')], default=10),
        ),
    ]
