# Generated by Django 4.2.16 on 2024-10-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0038_booking_regularity_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
    ]
