# Generated by Django 4.2.16 on 2024-10-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0039_remove_booking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='regularity',
            new_name='regularity_option',
        ),
    ]
