# Generated by Django 4.2.16 on 2024-10-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_rename_regularity_booking_regularity_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
