# Generated by Django 4.2.16 on 2024-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_booking_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
