# Generated by Django 4.2.16 on 2024-11-27 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0042_booking_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_cleaners',
            field=models.ManyToManyField(blank=True, default=None, related_name='booking_preferred_cleaners', to=settings.AUTH_USER_MODEL),
        ),
    ]
