# Generated by Django 4.2.16 on 2024-12-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0043_booking_preferred_cleaners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='feedback_for_cleaner',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='feedback_for_client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='feedback_tags_for_cleaner',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='feedback_tags_for_client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='score_for_cleaner',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='score_for_client',
        ),
        migrations.DeleteModel(
            name='FeedbackTagForCleaner',
        ),
        migrations.DeleteModel(
            name='FeedbackTagForClient',
        ),
    ]
