# Generated by Django 4.2.16 on 2024-12-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0044_remove_booking_feedback_for_cleaner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveIntegerField(choices=[(10, 'Not paid'), (20, 'Partially paid'), (30, 'Paid')], default=10),
        ),
    ]
