# Generated by Django 4.2.16 on 2024-12-18 00:14

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0045_remove_booking_is_paid_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='short_id',
            field=models.PositiveIntegerField(default=apps.bookings.models.generate_unique_numeric_id,
                                              editable=False, null=True),
        ),
    ]
