# Generated by Django 4.2.16 on 2024-12-18 00:14

from django.db import migrations
import random


def get_id(booking_model):
    while True:
        new_id = random.randint(100000, 9999999)
        if not booking_model.objects.filter(id=new_id).exists():
            return new_id


def generate_unique_numeric_id(apps, schema_editor):
    booking_model = apps.get_model('bookings', 'Booking')
    for booking in booking_model.objects.all():
        booking.short_id = get_id(booking_model)
        booking.save(update_fields=["short_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0046_booking_short_id'),
    ]

    operations = [
        migrations.RunPython(generate_unique_numeric_id, reverse_code=migrations.RunPython.noop),
    ]
