# Generated by Django 4.2.16 on 2024-12-18 00:15

import apps.bookings.models
from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0047_auto_20241218_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='short_id',
            field=models.PositiveIntegerField(default=apps.bookings.models.generate_unique_numeric_id,
                                              editable=False, unique=True),
        ),
    ]
