# Generated by Django 4.2.1 on 2023-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_regionzipcode_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='slug',
        ),
    ]
