# Generated by Django 4.2.1 on 2023-06-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_country_alter_regionzipcode_unique_together_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=128, null=True),
        ),
    ]
