# Generated by Django 4.2.1 on 2023-07-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_regionzipcode_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionzipcode',
            name='zip_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.zipcode'),
        ),
    ]
