# Generated by Django 4.2.1 on 2023-05-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_discountcode_booking_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
