# Generated by Django 4.2.1 on 2023-05-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingservice',
            old_name='company_service_fee_reference',
            new_name='company_service_fee',
        ),
        migrations.RenameField(
            model_name='bookingservice',
            old_name='service_fee_reference',
            new_name='service_fee',
        ),
    ]
