# Generated by Django 4.2.1 on 2023-05-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_company_service_fee_reference_bookingservice_company_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'In work'), (30, 'Completed'), (40, 'Rejected'), (50, 'Cancelled by client')], default=10),
        ),
    ]
