# Generated by Django 4.2.1 on 2023-05-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_accepted',
        ),
    ]
