# Generated by Django 4.2.1 on 2023-05-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='user',
        ),
    ]
