# Generated by Django 4.2.1 on 2023-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_rename_client_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
