# Generated by Django 4.2.1 on 2023-06-17 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0010_bookingmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingMessage',
            new_name='BookingChatMessage',
        ),
    ]
