# Generated by Django 4.2.1 on 2023-06-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_rename_bookingmessage_bookingchatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingchatmessage',
            old_name='message',
            new_name='text',
        ),
    ]
