# Generated by Django 4.2.1 on 2023-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_rename_user_booking_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
