# Generated by Django 4.2.1 on 2023-07-03 00:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_regionzipcode_unique_together'),
        ('users', '0008_usersession'),
        ('bookings', '0024_booking_user_session_alter_booking_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingZipCodeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersession')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
