# Generated by Django 4.2.1 on 2023-07-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_bookingzipcodesearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='regularity_type',
        ),
    ]
