# Generated by Django 4.2.1 on 2023-07-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_alter_booking_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='place_type',
            field=models.PositiveIntegerField(choices=[(10, 'Apartment'), (20, 'House'), (30, 'Commercial')], default=10),
        ),
    ]
