# Generated by Django 4.2.1 on 2023-07-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_booking_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
