# Generated by Django 4.2.1 on 2023-07-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_booking_stripe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='area_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='bathrooms_nmb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='bedrooms_nmb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
