# Generated by Django 4.2.1 on 2023-07-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_booking_area_size_booking_bathrooms_nmb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'In work'), (30, 'Completed'), (40, 'Cancelled by Company'), (50, 'Cancelled by Service'), (60, 'Cancelled by client')], default=10),
        ),
        migrations.AlterField(
            model_name='bookingstatuschange',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'In work'), (30, 'Completed'), (40, 'Cancelled by Company'), (50, 'Cancelled by Service'), (60, 'Cancelled by client')]),
        ),
    ]
