# Generated by Django 4.2.1 on 2023-06-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='channel',
        ),
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
    ]
