# Generated by Django 4.2.1 on 2023-06-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_is_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='to_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='to_phone',
            new_name='phone',
        ),
    ]
