# Generated by Django 4.2.1 on 2023-07-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
