# Generated by Django 4.2.1 on 2023-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationtemplate_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='channel',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'SMS'), (20, 'Email')], default=None, null=True),
        ),
    ]
