# Generated by Django 4.2.1 on 2023-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtemplate_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
